### ISSUE TITLE
Update application to version 1.0 of activity tracker it is based on 

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-client#6]
With version 1.0 of the "activity tracker" released in the meantime, it would be great to merge these latest developments into this application

**Comment by tmfrnz** [comment]
- [x] copy new version code as new branch

indicators

- [ ] add indicator views c95b892d4e68c48e7028d24ec9e5bc358450c198
- [ ] actionlist: show related indicators in action list 7675e4fa9070bc9cb224a15e93c249dc54b8691c
- [ ] actionlist allow filtering actions by indicators fb0bf019c25e67268ed98b19dd129570a2589696
- [ ] actionlist: allow linking indicators to actions from action list 474eef36895b83761e52a9e3609a84f31cc0c89f
- [ ] add indicators to action views 7db1d16a148c660b72d4582b35c6e46e2848d150

config/labels

- [ ] update labels eb15c8782ab191984a20bf7dfc4b5a0e65e18fad, f27f0f080064b45c80215087f908a9b250b916c0
- [ ] contact: add "contact" actor type 444545ea6d1b25994b0dc3d8fa2d2c50b7363c80, 24c11dd4cba0d4fa691f16a9c6bb7d1ab1c0e23e
- [ ] change phone from input to text: 49faebf342ad12bbdf14c242e4d81448131469cf
- [ ] naming: cc57708c126d2c9d5e2e59a25eba4a281c0f5da7
- [ ] config: 8ff3bee8a621a8918a1256cb9a2c77a3823be738, d57184aa7a2b272d3b1b864d3d17c5a3b6894649, 5bbcad96fb9303a66888c41ef9c90cac73cb5d01, d809198d8cf800cc1de8ceccd411ba76a86a5efe
- [ ] list sidebar config: e346c61fb8b76cd91195a106a4480b8f36b2c6fa

actors/actions

- [ ] allow adding actions from actor view 103c509382d97a6be96a8e182127d88f8413a20d
- [ ] allow different parent type for actions c61419654fb78cf2514d8aa8c9099c93ffb59b3c
- [ ] allow top & sub actions (see above, ef9d8fe9d1b67303b6366f332e68cc59e8ba496a, e2ae642078874e1f731cf799f8f63f14bcc8b502, 0f47ad3378cac4f7fe95419eaee0639e2ae31613)
- [ ] actor-memberships should be configured in client config not in db 86cd7b5cd563f36f840f3049ccbca6b59218115b
- [ ] fix for non-existing actor-actions f2e0a17fe1524bb427c55ffb64411bd712915277
- [ ] allow inverse membership dd22cebfc1170856071e98c136988efa4c0b696e, c3dc4b2599beda5d76fc147583003e2e0c122ca6

users

- [ ] allow assigning users to measures and actors (4c254745340b998211b1b91f69ad405d1763ed0e, f5300d75f0872738c1aba066e0303a51c8c1f143, 00d5b36c2fef2368bff886ffe9a85550600b90cc)
- [ ] allow linking users with activity from activity list e922bcfdaec383b57ff54828963e45746630f7d8
- [ ] filter user list by actions 6868b0decdeb82e11025b488910ef94e80f48d1d

map

- [ ] map: fix map config 3286df0b4b3e1204cf8c1251c1b905d83d2d1ef3
- [ ] map: remove target option bd3a0d878dcf96a31b59d15856c9a1f7c502f0f3

other 

- [ ] improve "new entity modal" d2f6b6eb371ec563949a5a89f16a879d16d472ff
- [ ] search: filter by description f4dac08dc59d8cccd8c72294a21411b355a02f64
- [ ] description in edit options (related to previous?, 3ee15e53de7cb95f286bdf76964f45332108af8a)



likely not needed

- [ ] mobile support 66d1bdf2bebd9f6e34844f15afebd6113a343b14

**Comment by tmfrnz** [comment]
make sure things are working as expected

## simple (without connections)

### single views

- [ ] new action
- [ ] view action 
- [ ] edit action

- [ ] new actor
- [ ] view actor
- [ ] edit actor

- [ ] new indicator
- [ ] view indicator
- [ ] edit indicator

- [ ] view user
- [ ] edit user

### list views (incl filtering by attribute)

- [ ] list actions
- [ ] list actors
- [ ] list users
- [ ] list indicators

## connections

### single views (both ways, from edit view)

- [ ] actor-actions (also from actor view)
- [ ] action-actors (targets)
- [ ] action-actions (top/sub-actions)
- [ ] memberships (actor-actors)
- [ ] user-actions
- [ ] user-actors

### list views (both ways)

- [ ] actor-actions
- [ ] action-actors (targets)
- [ ] action-actions (top/sub-actions)
- [ ] memberships (actor-actors)
- [ ] user-actions
- [ ] user-actors

**Comment by tmfrnz** [comment]
## enhancements

### list views

- [ ] action lists: show by actor/target/user (where config allows)
- [ ] actor lists: consider use of "include membership option"
- [ ] actor lists: do not offer actor/target connections if not configured (ie Groups, Regions)
- [ ] actor lists: consider showing by user (where config allows)
